### PR TITLE
Master

### PR DESCRIPTION
**Pull request by lxk0301**

### CODE REVIEW

**Comment by lxk0301** [comment]
解决冲突

**Comment by bsZzz** [comment]
> 解决冲突
可以用这个教程将上游仓库合并到复刻
https://help.github.com/cn/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

**Comment by lxk0301** [comment]
> > 解决冲突
> > 可以用这个教程将上游仓库合并到复刻
> > https://help.github.com/cn/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork
> 
> 就不用创建pull request了

好的

**Comment by lxk0301** [comment]
根据上面的链接操作
解决冲突
可以用这个教程将上游仓库合并到复刻
https://help.github.com/cn/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork
每次都会发生下图的样子, 而且指的都是同样两个问题
image

**Pull request merged**
